name: 'Setup ActionFlow environment'
description: 'Setup a ActionFlow environment and add it to the PATH'
author: 'GitHub'
inputs:
  flow-version:
    description: 'The ActionFlow version to download (if necessary) and use. Supports semver spec and ranges.'
  check-latest:
    description: 'Set this option to true if you want the action to always check for the latest available version that satisfies the version spec'
    default: false
  cache:
    description: Used to specify whether caching is needed. Set to true, if you'd like to enable caching.
    default: false
  cache-dependency-path:
    description: 'Used to specify the path to a dependency file - go.sum'
  architecture:
    description: 'Target architecture for Go to use. Examples: x86, x64. Will use system architecture by default.'
outputs:
  flow-version:
    description: 'The installed Go version. Useful when given a version range as input.'
  cache-hit:
    description: 'A boolean value to indicate if a cache was hit'
runs:
  using: 'node16'
  main: 'dist/setup/index.js'
  post: 'dist/cache-save/index.js'
  post-if: success()
